server:
  port: 8280

spring:
  profiles:
    active: security
  application:
    name: billiards-rank-api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 쿼리를 읽기 쉽게 포맷하여 보여줍니다.

